[default]
address = "0.0.0.0"
port = 8000

[default.switches]
kindle = true
weather = true
bark = true
let_server_run = true

[default.kindle]
style = "<0,1,2>"
fonts.main = ""
fonts.weather = ""
fonts.status = ""

[default.weather]
cron = "" # second minute hour day month day_of_week year
location = ""
key = ""

[default.bark]
url = ""

[default.let_server_run]
interval = 60
token = ""

[default.let_server_run.executors]
echo = { t = "echo", c = "" }
